library(rmarkdown)
library(fs)
library(beepr)
render("J:/R/Others/pkgstats/daily_reports.Rmd")
file_copy("J:/R/Others/pkgstats/daily_reports.html", 
                      "C:/Users/HP/Desktop/daily_reports.html")
beep(3)
file_delete("J:/R/Others/pkgstats/daily_reports.html")
file_chmod("C:/Users/HP/Desktop/daily_reports.html", "a+rwx")
browseURL("C:/Users/HP/Desktop/daily_reports.html")
Sys.sleep(100)
file_delete("C:/Users/HP/Desktop/daily_reports.html")
file_chmod("J:/R/Others/pkgstats/country_wise.log", "a+rwx")
file_delete("J:/R/Others/pkgstats/country_wise.log")
